development:
#  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
#  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
#  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_client_id: OM1ane00j0RHP2kMmP4Y7fJPa9axQuLi
  auth0_client_secret: _hBzYoQqQwmIRHL-8ABAAY02XbcWWMLIG4YqOsA-EC1gUzdCW8uSAt5KQ4RpQCli
  auth0_domain: dev-o5rqyf1u.us.auth0.com


test:
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>

production:
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
